version: '3.2'

services:

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.5.3
    container_name: filebeat
    user: root
    networks:
      - logging-approach
    environment:
      - strict.perms=false
    volumes:
      - './filebeat.yml:/usr/share/filebeat/filebeat.yml:ro'
      - './data:/usr/share/filebeat/data:rw'
      - './var/log/busybox:/usr/share/services/busybox'
      #- '/home/ubuntu/.pm2/logs:/usr/share/services/node'
    command: filebeat -e
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
  busybox:
    image: busybox
    networks:
      - logging-approach
    command:
      - /bin/sh
      - -c
      - >
        mkdir -p /var/log/
        i=0;
        rotate=0;
        while true;
        do
          echo "INFO log file $((i)) rotated for busybox app log"
          while [ "$((rotate))" -lt "500" ]
          do
            echo "$(date) INFO $i busybox app log" >> /var/log/$((i)).log;
            rotate=$((rotate + 1))
            sleep 0.01;
          done
          i=$((i+1));
          rotate=0;
        done
    volumes:
      - './var/log/busybox:/var/log'
networks:
  logging-approach:
    external: true