filebeat.inputs:
  - type: log
    enabled: true
    tags:
      - app_1_busybox
    paths:
      - /usr/share/services/busybox/*.log

  - type: log
    enabled: true
    tags:
      - app_1_pm2
    paths:
      - /usr/share/services/node/*.log

output.kafka:
  version: 0.10.2.1
  hosts: ["broker:29092"]
  topic: 'logtopic'
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000